
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-Disallow","number":51,"title":"Fixed disallowing users to navigate to unjoined commons","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/51"},{"author":{"id":"U_kgDOBdCCBA","is_bot":false,"login":"jasontnguyen","name":"Jason Nguyen"},"headRefName":"JN-CreateButton","number":50,"title":"Feature: Added Create Announcement Button (Placeholder Page)","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/50"},{"author":{"id":"U_kgDOBdCCBA","is_bot":false,"login":"jasontnguyen","name":"Jason Nguyen"},"headRefName":"JN-ShowAnnouncementsTable","number":48,"title":"Show List of Announcements For Certain Commons","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/48"},{"author":{"id":"U_kgDOBckqqw","is_bot":false,"login":"CongruiDu","name":"RayDu"},"headRefName":"rd-home","number":46,"title":"Improve Homepage UI","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/46"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-UpdatePomXML","number":45,"title":"Updated pom.xml so partial pitest runs work","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/45"},{"author":{"id":"U_kgDOBdCCBA","is_bot":false,"login":"jasontnguyen","name":"Jason Nguyen"},"headRefName":"JN-AnnouncementsBackend","number":39,"title":"Creating Announcements No Longer Returning Null For EndDate ","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/39"},{"author":{"id":"U_kgDOB2-2pQ","is_bot":false,"login":"nevetsle","name":""},"headRefName":"SL-LeaveButton","number":38,"title":"Leave Button Implemented (FRONTEND)","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/38"},{"author":{"id":"U_kgDOBdHhNQ","is_bot":false,"login":"GarvinYoung","name":""},"headRefName":"GY-TrackCommitInfo","number":37,"title":"Github Commit Info Accessible Through /api/systemInfo API Call","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/37"}]
