
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOBnFWjw","is_bot":false,"login":"Baimin-Wang","name":""},"headRefName":"BW-ShowAnnouncements","number":68,"title":"F3 Add Assignment to the Commons OverviewPage","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/68"}]
