
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-5
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-5
pull_requests: [{"author":{"id":"U_kgDOBdHhNQ","is_bot":false,"login":"GarvinYoung","name":""},"headRefName":"GY-ShowSwaggerUILink","number":30,"title":"SwaggerUILink Correctly Appears Depending on Corresponding Dokku Env Variable","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/30"},{"author":{"id":"U_kgDOBdCCBA","is_bot":false,"login":"jasontnguyen","name":"Jason Nguyen"},"headRefName":"JN-AnnouncementsIndexPagePath","number":29,"title":"Issue F2: Add Announcement Button to Admin Commons List","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/29"},{"author":{"id":"U_kgDOBdHhNQ","is_bot":false,"login":"GarvinYoung","name":""},"headRefName":"GY-StartDateBug","number":28,"title":"Fixed Bug with Incorrect Starting Date on Creating Commons Form","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5/pull/28"}]
